### ISSUE TITLE
why use bash?

### ISSUE THREAD

**Issue by drozdowsky** [dylanaraps/pash#5]
I like the idea but wouldn't POSIX sh make it more portable?
Just asking, currently I have no bash on my metal :)

**Comment by dylanaraps** [comment]
It's in the works as I don't need bash either. ;)

**Comment by dylanaraps** [comment]
Tada: https://github.com/dylanaraps/pash/blob/master/pash-posix

This should be identical to the `bash` version with only minor differences (`tree` command instead of doing it in the shell for example). I'd still like to do some clean up and add some comments (*there are some nice tricks in the port*).

Please test it and let me know if you come across any issues. :)

Once I'm 100% happy with the POSIX port I'll name it `pash` and rename the `bash` version to something else. It'll be nice to keep both versions around as it's a great comparison between `bash`/`sh`.

**Comment by dylanaraps** [comment]
POSIX `sh` version is now the default.
